name: Simple Test
on:
  push:
    branches:
      - main
jobs:
  Simple-Test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        run: go test ./pyutil
